// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EmotionIcon: typeof import('./src/components/m-emotion/emotionIcon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MBackTop: typeof import('./src/components/m-back-top/index.vue')['default']
    MEmotion: typeof import('./src/components/m-emotion/index.vue')['default']
    MLoading: typeof import('./src/components/m-loading/index.vue')['default']
    MPopupPicker: typeof import('./src/components/m-popup-picker/index.vue')['default']
    MScrollBackTop: typeof import('./src/components/m-scroll-back-top/index.vue')['default']
    MSignatureBoard: typeof import('./src/components/m-signature-board/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignatureBoard: typeof import('./src/components/m-signature-board/SignatureBoard.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}

export {}
