// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EmotionIcon: typeof import('./src/components/m-emotion/emotionIcon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MBackTop: typeof import('./src/components/m-back-top/index.vue')['default']
    MEmotion: typeof import('./src/components/m-emotion/index.vue')['default']
    MLoading: typeof import('./src/components/m-loading/index.vue')['default']
    MPopupPicker: typeof import('./src/components/m-popup-picker/index.vue')['default']
    MRate: typeof import('./src/components/m-rate/index.vue')['default']
    MScrollBackTop: typeof import('./src/components/m-scroll-back-top/index.vue')['default']
    PropBackTop: typeof import('./src/components/m-back-top/PropBackTop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanIcon: typeof import('vant/es')['Icon']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}

export {}
