name: build and deploy # 自动部署的名称

# 当 master 分支 push 代码的时候触发 workflow
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest # 运行环境，告诉它运行在什么环境
    steps: # 步骤
      # 第一步：下载仓库代码(CI/CD拉取代码到自己的本地)
      - uses: actions/checkout@v3

      # 第二步：打包构建
      - run: npx pnpm install --no-frozen-lockfile # 安装打包依赖
      - run: npx pnpm run build # 打包

      # 发布到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 访问秘钥
          PUBLISH_BRANCH: gh-pages # 推送分支
          PUBLISH_DIR: ./dist # 部署目录
